### ISSUE TITLE
Standalone examples.md has a bad link for obtaining API key.

### ISSUE THREAD

**Issue by CaptainMcCrank** [NVIDIA/GenerativeAIExamples#111]
1. Visit https://github.com/NVIDIA/GenerativeAIExamples/tree/main/examples
2. Click on link embedded in step 3. (Follow the steps mentioned here to get this.)   Notice the 404 for the referenced file: https://github.com/NVIDIA/GenerativeAIExamples/blob/main/docs/ai-foundation-models.md#get-an-api-key-for-the-mixtral-8x7b-instruct-api-endpoint

**Comment by shubhadeepd** [comment]
Thanks for reporting this bug.
@mikemckiernan to help fix this.

**Comment by shubhadeepd** [comment]
@CaptainMcCrank here is the correct until we fix this in our codebase
https://nvidia.github.io/GenerativeAIExamples/latest/api-catalog.html#get-an-api-key-for-the-mixtral-8x7b-instruct-api-endpoint

**Comment by mikemckiernan** [comment]
The 404 is addressed. Thanks again for letting us know about the issue!
