### ISSUE TITLE
You will need to set `allow_dangerous_deserialization` to `True`

### ISSUE THREAD

**Issue by DennisFaucher** [NVIDIA/GenerativeAIExamples#114]
Example 10_RAG_for_HTML_docs_with_Langchain_NVIDIA_AI_Endpoints fails with error:

ValueError: The de-serialization relies loading a pickle file. Pickle files can be modified to deliver a malicious payload that results in execution of arbitrary code on your machine.You will need to set `allow_dangerous_deserialization` to `True` to enable deserialization. If you do this, make sure that you trust the source of the data. For example, if you are loading a file that you created, and no that no one else has modified the file, then this is safe to do. Do not set this to `True` if you are loading a file from an untrusted source (e.g., some random site on the internet.).

**Comment by shubhadeepd** [comment]
Thank you for noticing this. 
We have fixed this.
https://github.com/NVIDIA/GenerativeAIExamples/blob/main/RAG/notebooks/langchain/RAG_for_HTML_docs_with_Langchain_NVIDIA_AI_Endpoints.ipynb
