### ISSUE TITLE
upload_pdf_files does not check for file type or format

### ISSUE THREAD

**Issue by OlegSudakov** [NVIDIA/GenerativeAIExamples#12]
Experimenting with notebooks can create .`ipynb_checkpoints` folder in RetrievalAugmentedGeneration/notebooks/dataset. 
![image](https://github.com/NVIDIA/GenerativeAIExamples/assets/3092478/232727d6-0411-47c4-97dc-3f457ac24eab)

This will cause upload_pdf_files function to fail when increasing `NUM_DOCS_TO_UPLOAD`. The issue does not occur with default `NUM_DOCS_TO_UPLOAD` (100), as the number of .pdf files in dataset.zip is greater than 100.

![image](https://github.com/NVIDIA/GenerativeAIExamples/assets/3092478/61521e41-2486-489b-bc48-7384b2b32d40)

**Comment by shubhadeepd** [comment]
@OlegSudakov Thanks for pointing this bug out.
This should have been fixed with the latest v0.2.0 release. 
https://github.com/NVIDIA/GenerativeAIExamples/blob/main/notebooks/05_dataloader.ipynb
Feel free to close this issue after checking.
