### ISSUE TITLE
Asking question which does not have a relevant snippet in the knowledge base leads to frontend error

### ISSUE THREAD

**Issue by OlegSudakov** [NVIDIA/GenerativeAIExamples#13]
Asking a question, unrelated to knowledge base content, causes frontend to fail with error.

Without knowledge base:
![image](https://github.com/NVIDIA/GenerativeAIExamples/assets/3092478/476e809b-5e1b-41ff-9e66-fc164303787c)

With knowledge base:
![image](https://github.com/NVIDIA/GenerativeAIExamples/assets/3092478/a41f97b6-465c-457e-a124-08860fd1a52f)

**Comment by shubhadeepd** [comment]
@OlegSudakov Thanks for pointing this bug out.
This should have been fixed with the latest v0.2.0 release.
Can you please verify the same with latest codebase and close this issue?
