### ISSUE TITLE
services.chain-server.depends_on.nemollm-embedding Additional property required is not allowed

### ISSUE THREAD

**Issue by lhrm** [NVIDIA/GenerativeAIExamples#173]
I'm encountering an issue when I try to run docker compose build using the docker-compose.yml file provided in the RAG example. My Docker Compose version is v2.5.0, and the build process fails with the following error:

services.chain-server.depends_on.nemollm-embedding Additional property required is not allowed

It seems that the required property is causing the problem. Could someone help clarify the correct usage or suggest how to resolve this issue?

Thanks in advance for your help!

**Comment by Margo-Kim** [comment]
I experienced this when I was using docker compose v 2.18.0. I would recommend to upgrade your docker compose to the latest version. (v 2.29.2)

**Comment by shubhadeepd** [comment]
Thanks for reporting this.
We have added instructions explicitly to use compose version v2.29+ on the prerequisites page as part of https://github.com/NVIDIA/GenerativeAIExamples/issues/176. 
Please don't hesitate to let us know if you have any more issues after upgrading the compose version!
