### ISSUE TITLE
Errors when starting simple and advanced RAG examples

### ISSUE THREAD

**Issue by nvahmadi** [NVIDIA/GenerativeAIExamples#176]
Running RAG examples, both `simple_rag/langchain` and `advanced_rag/multi_turn_rag` throws an error when trying to start them as instructed with `docker compose up -d --build`.

Running `GenerativeAIExamples/RAG/examples/basic_rag/langchain` yields this error:
```
imported compose file [/data/Projects/GenerativeAIExamples/RAG/examples/local_deploy/docker-compose-vectordb.yaml /data/Projects/GenerativeAIExamples/RAG/examples/local_deploy/docker-compose-nim-ms.yaml] defines conflicting network default
```

Running `GenerativeAIExamples/RAG/examples/advanced_rag/multi_turn_rag` yields the same error:
```
imported compose file [/data/Projects/GenerativeAIExamples/RAG/examples/local_deploy/docker-compose-vectordb.yaml /data/Projects/GenerativeAIExamples/RAG/examples/local_deploy/docker-compose-nim-ms.yaml] defines conflicting network default
```

I haven't tried the other examples yet, but they may throw similar errors. 
The main reason is that all 3 yaml files define their default network identically as:
```
networks:
  default:
    name: nvidia-rag
```

I tried defining the networks as external in all 3 yaml files as such:
```
networks:
  default:
    external: true
    name: nvidia-rag
```
and creating that network manually & externally in CLI via `docker network create nvidia-rag`, but that didn't help.

Is there an easy workaround?

**Comment by Margo-Kim** [comment]
Check your docker compose version. I tried with 2.20.0 version but it wasn't working for me but when I upgraded the docker compose version to 2.29.2, it started working

**Comment by shubhadeepd** [comment]
> Check your docker compose version. I tried with 2.20.0 version but it wasn't working for me but when I upgraded the docker compose version to 2.29.2, it started working

Thanks. We have added this instruction explicitly in the prerequisites page as part of [this PR](https://github.com/NVIDIA/GenerativeAIExamples/issues/176). Let us know if you face further issues after upgrading the compose version!
