### ISSUE TITLE
NGC_API_KEY variable is not set

### ISSUE THREAD

**Issue by efealioksuz** [NVIDIA/GenerativeAIExamples#209]
When I try to compose the multi_turn_rag, I get the warning:
` WARN[0000] The "NGC_API_KEY" variable is not set. Defaulting to a blank string. 
Cannot connect to the Docker daemon at unix:///Users/efealioksuz/.docker/run/docker.sock. Is the docker daemon running?`.
Now, I have got my NVIDIA API key and export it as an environment variable as explained in the readme.file of multi_turn_rag;
`export NVIDIA_API_KEY="nvapi-<...>"`.
However, I don't see any explanations about  "NGC_API_KEY", and where to get that.

**Comment by dglogo** [comment]
See prerequisites: https://github.com/NVIDIA/GenerativeAIExamples/tree/main/RAG/examples/advanced_rag/multi_turn_rag#prerequisites

**Comment by manjunathshiva** [comment]
Steps has been provided in the README  file under NVIDIA/GenerativeAIExamples ( https://github.com/NVIDIA/GenerativeAIExamples/blob/main/README.md )

Get your NVIDIA API key.

Go to the [NVIDIA API Catalog](https://build.ngc.nvidia.com/explore/).
Select any model.
Click Get API Key.
Run:
export NVIDIA_API_KEY=nvapi-...
