### ISSUE TITLE
Error message has incorrect model engine name of nemo-infer instead of ai-playground

### ISSUE THREAD

**Issue by nathankw** [NVIDIA/GenerativeAIExamples#21]
RetrievalAugmentedGeneration.common.utils.get_llm() reports the incorrect model_engine name in the last line of the function in error string. Says "Supported engines are triton-trt-llm and nemo-infer", but should say "Supported engines are triton-trt-llm and ai-playground".

In the config.yaml file, we must specify llm.model_engine as one of [triton-trt-llm, ai-playground].

**Comment by mohammedpithapur** [comment]
hii i am new here i have corrected the error msg now i am confused in config.yaml , previously it was model_engine="triton-trt-llm", now should i add both triton-trt-llm, ai-playground in a list or just separate them by comma 
![Screenshot 2024-01-07 122139](https://github.com/NVIDIA/GenerativeAIExamples/assets/72722182/a7fdb9a7-682f-417b-834d-9b0ede330d42)

**Comment by shubhadeepd** [comment]
@mohammedpithapur  Thanks for fixing the error message!
It should be either
`model_engine: "triton-trt-llm"`
OR
`model_engine: "ai-playground"`

**Comment by mohammedpithapur** [comment]
Can you suggest how I can do it, sorry I am new

**Comment by shubhadeepd** [comment]
@mohammedpithapur we now have a dedicated example to showcase AI playground in latest codebase!
No config file changes are needed (this avoids the confusion you faced).
Please checkout the example here
https://github.com/NVIDIA/GenerativeAIExamples/blob/main/RetrievalAugmentedGeneration/README.md#1-qa-chatbot----nvidia-ai-foundation-inference-endpoint
