### ISSUE TITLE
Can't connect to the pgvector database with the developer RAG

### ISSUE THREAD

**Issue by Frank-Che** [NVIDIA/GenerativeAIExamples#37]
Steps to reproduce:
1. In compose.env, set POSTGRES_PASSWORD=password; POSTGRES_USER=pgadmin; POSTGRES_DB=api.
2. Start the developer RAG with docker-compose-pgvector.yaml
3. On the developer RAG UI, swith to the 'kb' page, click 'Add file' to upload a pdf file.

Problem description: The UI show 'Error' for the document upload action. In the logs, saw these messages:
# chain-server          | connection to server at "xx.xx.xx.xx", port 5432 failed: FATAL:  no pg_hba.conf entry for host "192.168.0.1", user "pgadmin", database "pgadmin", no encryption

Root cause: it seems the connection string is not correctly specified in the code. Database name should not be the same as the user name.

Other information: if the default user name 'postgres' is used, then this problem will not happen.

**Comment by nv-pranjald** [comment]
Thanks @Frank-Che , URL was hardcoded for PGvector to run on same system. 
This is fixed and you can use environment variable to specify port and host IP from `compose.env`

```
export POSTGRES_HOST_IP=pgvector
export POSTGRES_PORT_NUMBER=5432
```
