### ISSUE TITLE
Data not written to the specified pgvector database with the developer RAG

### ISSUE THREAD

**Issue by Frank-Che** [NVIDIA/GenerativeAIExamples#38]
Steps to reproduce:
1. In compose.env, set POSTGRES_PASSWORD=password; POSTGRES_USER=postgres; POSTGRES_DB=mydb.
2. Start the developer RAG with docker-compose-pgvector.yaml
3. On the developer RAG UI, swith to the 'kb' page, click 'Add file' to upload a pdf file.
4. Connect to the created pgvector database with UI tools like 'pgAdmin'. Check the vector data written to the database.

Problem description: vector data was not written to the user speicified database 'mydb', but written to another database named 'vector_db'. And it seems the name 'vector_db' is hard-coded.

Expected result: vector data should be written to the database user specified in the compose.env file.

**Comment by nv-pranjald** [comment]
Thanks @Frank-Che for opening the issue. 
As you mentioned database name was hardcoded to `vector_db`. Now we're taking this value from environment variable `POSTGRES_DB`.
