### ISSUE TITLE
Missing url

### ISSUE THREAD

**Issue by catsudon** [NVIDIA/GenerativeAIExamples#99]
on [rag in 5 minutes example]( https://github.com/NVIDIA/GenerativeAIExamples/blob/main/examples/README.md#rag-in-5-minutes-example)

![Screenshot 2024-04-07 221636](https://github.com/NVIDIA/GenerativeAIExamples/assets/52562864/e5028d17-5208-4d04-94b2-6ebf4221e3ad)

this hyperlink linked to [here](https://github.com/NVIDIA/GenerativeAIExamples/blob/main/docs/ai-foundation-models.md#get-an-api-key-for-the-mixtral-8x7b-instruct-api-endpoint) which has no file.
![Screenshot 2024-04-07 221809](https://github.com/NVIDIA/GenerativeAIExamples/assets/52562864/c561b749-e3be-489c-ada8-f8c18476d7ce)

**Comment by shubhadeepd** [comment]
Thank you. We will fix this in upcoming release.
Link to obtaining API key can be found here
https://nvidia.github.io/GenerativeAIExamples/latest/api-catalog.html#get-an-api-key-for-the-mixtral-8x7b-instruct-api-endpoint

**Comment by mikemckiernan** [comment]
The URL is fixed.  Thank you for letting us know about the issue!
